/*
** EPITECH PROJECT, 2023
** zombie_sounds_config.h
** File description:
** desc
*/
#ifndef zombie_sounds_config
    #define zombie_sounds_config

    #include <sounds.h>
    #include <t_ctype.h>
    #include <entity_sounds.h>

    static const entity_sound_s zombie_sound_config[] = {
            {
                "zombie_damage_1",
                sound_damage,
                "assets/sound/zombie/damage/zombie_damage_1.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_damage_2",
                sound_damage,
                "assets/sound/zombie/damage/zombie_damage_2.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_damage_3",
                sound_damage,
                "assets/sound/zombie/damage/zombie_damage_3.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_death_1",
                sound_death,
                "assets/sound/zombie/death/zombie_death_1.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_death_2",
                sound_death,
                "assets/sound/zombie/death/zombie_death_2.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_death_3",
                sound_death,
                "assets/sound/zombie/death/zombie_death_3.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_idle_1",
                sound_idle,
                "assets/sound/zombie/idle/zombie-idle-1.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_melee_1",
                sound_melee,
                "assets/sound/zombie/melee/zombie_melee_1.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_melee_2",
                sound_melee,
                "assets/sound/zombie/melee/zombie_melee_2.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_melee_3",
                sound_melee,
                "assets/sound/zombie/melee/zombie_melee_3.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_melee_4",
                sound_melee,
                "assets/sound/zombie/melee/zombie_melee_4.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_trigger_1",
                sound_trigger,
                "assets/sound/zombie/trigger/zombie_trigger_1.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_trigger_2",
                sound_trigger,
                "assets/sound/zombie/trigger/zombie_trigger_2.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_trigger_3",
                sound_trigger,
                "assets/sound/zombie/trigger/zombie_trigger_3.ogg",
                250,
                100,
                false,
                false
            },
            {
                "zombie_trigger_4",
                sound_trigger,
                "assets/sound/zombie/trigger/zombie_trigger_4.ogg",
                250,
                100,
                false,
                false
            },
            {
                NULL,
                sound_unknown,
                NULL,
                0,
                0,
                false,
                false
            }
    };

#endif //zombie_sounds_config
